/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ejfiazcijdjzovuxkpth"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqZmlhemNpamRqem92dXhrcHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNzgyODcsImV4cCI6MjA4MDk1NDI4N30.LITK1llR3k4E-LArGg9svZ4wpCq9V6Ko9vMtujH-B8o"